# Generated by Buildr 1.5.3, change to your liking


# Version number for this release
VERSION_NUMBER = "1.0.1"
# Group identifier for your projects
GROUP = "BuildrSample"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"
repositories.release_to[:options] = {:digests => [:md5, :sha1, :sha512]}

if VERSION_NUMBER =~ /SNAPSHOT/
else
#    require "buildr/gpg"
end

desc "The Buildrsample project"
define "BuildrSample" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  define "proj1" do
    compile.with # Add classpath dependencies
    package(:jar)
  end

  define "proj2" do
    compile.with # Add classpath dependencies
    package(:jar)
  end
end
